### ISSUE TITLE
Possible Names

### ISSUE THREAD

**Issue by mecwerks** [OpenRhythm/OpenRhythm#1]
Let's Rock!

**Comment by Salamandar** [comment]
A more classical name would be FoF++ :)

**Comment by mdsitton** [comment]
Classic maybe? but that name would be better suited for an exact original FoF clone written in C++. This wont be an exact clone, so I don't think it would be a good name... Despite that I have added it to the list of suggestions so far. (it includes them all even the sarcastic ones...)
https://msitton.com/pad/p/mg_names

**Comment by mdsitton** [comment]
So what do you think of the name Reprise?

**Comment by Salamandar** [comment]
Well it seems we can close the issue for now as OpenRhythm seems accepted ;)

**Comment by mdsitton** [comment]
yeah i've been meaning to close this for a couple days :P
