### ISSUE TITLE
Args parsing

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#13]
There's a great lib here : http://optionparser.sourceforge.net
- Header only 
- seems to create the "--help" too
- no need to loop on all args, seems pretty easy

It's not gonna be a huge bit of code though ;)

**Comment by mdsitton** [comment]
Yeah i have been looking at various options for this for a little while now but never really got to comparing the different options very well.

**Comment by Salamandar** [comment]
Well i searched the different existing libs and this one seems the easies to use !

**Comment by Salamandar** [comment]
You can define " hard-coded" args in an array, plus parse manually other args

**Comment by mdsitton** [comment]
Honestly I don't like the syntax of any of the major options out there.
The syntax of this parser is pretty cool though:
https://github.com/aardvarkk/argh

**Comment by mdsitton** [comment]
If we have to I don't mind just implementing my own lol. They aren't very complex to do honestly. I could also just fork that one and throw it into our codebase and clean it up a bit. :P

**Comment by Salamandar** [comment]
Sure, I wanted to write my own lib too, and also f4r configuration files. But hell, there are so many good libs out there ^^

**Comment by mdsitton** [comment]
Well for config files i was wanting to use json or YAML.

**Comment by mdsitton** [comment]
We should probably make another issue about config files

**Comment by mdsitton** [comment]
ok issue #15 is for config files and the config system

**Comment by Salamandar** [comment]
Great !

**Comment by Salamandar** [comment]
I checked out Argh, seems cool, the syntax is pretty clear. But there are some problems :
* no apparent support for "bad args"
* only "dynamic" args definitions, can't use a header to define the args (header parsed for the html doc :p )

**Comment by mdsitton** [comment]
I dont really want to use Argh because its not really a well used library, and if thats the case i'd just rather do something ourselfs. But I mainly just mentioned it as a example of some nicer looking syntax :P

**Comment by Salamandar** [comment]
Hmm on the other hand OptionParser let us do a lot of job. I have to parse myself the integer args… :p

**Comment by Salamandar** [comment]
To be fair I think I'm gonna rewrite optionparser x)

**Comment by mdsitton** [comment]
One thing though what did you mean by "bad args"?

**Comment by Salamandar** [comment]
Well there are two things : "non-options" (things not preceded by `--` or `--option` ) such as filenames for gcc, and unknown options. Argh does not seem to support "out of the box" neither of them… And it does not support parameters for short options.
Anyway, i've almost finished to rewrite OptionParser.

**Comment by mdsitton** [comment]
@Salamandar So how is this going, you said you were going to write your own parser(or rewrite the other one)

**Comment by Salamandar** [comment]
Well it's going fine, I just had a really big existential issue about if it was relevant or not ^^

**Comment by Salamandar** [comment]
Finally OptionParser is just too overkill. TCLAP is pretty good (I just wrote a PR to TCLAP and may write a second to support multiple one-char flags for an option)

**Comment by mdsitton** [comment]
My problem with TCLAP is that it is largely unmaintained

**Comment by Salamandar** [comment]
Yeah that was my issue too. But some widely libs are unmaintained too. TCLAP does not seem buggy, and the authors seem quick to answer on sourceforge even if it's "i don't have much time but please make a patch !"

**Comment by mdsitton** [comment]
I still don't mind rolling our own

**Comment by Salamandar** [comment]
Well I think I'm gonna fork TCLAP on Github (and tell the original authors about it) so we can restart dev on it.

**Comment by Salamandar** [comment]
Finished with PR #32. Closing, we'll solve the possible problems in the PR.
