### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#14]
Gettext is usually used on UNIX systems with .po files, seems to be supported on Windows/OsX too, dunno.

**Comment by mdsitton** [comment]
Well FoFiX used gettext on windows and osx so i guess it will work? I'll look into this in a bit.

Translations are one of the things i really do want to get correct early on, along with proper unicode text rendering for UIs.

Text should definitely be stored as UTF-8 though that much i've decided :P

**Comment by Salamandar** [comment]
Utf-8 is life, yeah ^^ and seeing the awful text rendering issues (cant set fofix in french)... Yeah. Cant even unverstand how FoFiX has this kend of bugs...

**Comment by Salamandar** [comment]
Pushed Gettext support in 19f44ad.

**Comment by Salamandar** [comment]
Just so you know (if you don't already), all strings should be used like

    # File header :
    #include <libintl.h>
    #define _(STRING) gettext(STRING)

    _("the string to be translated")
    # Smth like
    m_logger->info(_("Loading MIDI"));

**Comment by Salamandar** [comment]
The initialization code is : 
```
    /* Setting the i18n environment */
    setlocale (LC_ALL, "");
    std::cout << LOCALE_DIR << std::endl;
    bindtextdomain ("openrhythm", LOCALE_DIR);
    textdomain ("openrhythm");
```
For now (not commited nor pushed) I just pasted this in the main(), but I'll have to find a better place for this. Maybe directly in a preferences/ directory, containing the preferences changes+reading+saving.

**Comment by Salamandar** [comment]
Ah yeah, and the bad news is that the POTFILES.in file has to contain the files list. Could not do that in CMake, and that's a shame.
