### ISSUE TITLE
Configuration and Config Files.

### ISSUE THREAD

**Issue by mdsitton** [OpenRhythm/OpenRhythm#15]
Currently there is nothing implemented to load, store or make available any sort of configuration options.

There needs to be some kind of central config class that allows you to get and set global configuration keys/values which will get automatically saved to the config file once changed.

The config file will probably be either JSON or YAML.

**Comment by Salamandar** [comment]
Yeah, YAML seems great for that. Great libs available, already widely used, supports comments, and internal references.
JSON has some upsides too like a better structuration, strings with quotes, and it does not need line feeds.

**Comment by mdsitton** [comment]
Really the only downside to json is the lack of support for comments, but technically we could add support for comments as a preprocessing step that we remove before decoding.

For the UI system I want to use JSON, because of its ease of network transmission. Mainly because I want to have multiplayer servers be able to do custom UI stuff.

**Comment by Salamandar** [comment]
Yeah, YAML is just not adapted to UI definition.
Why not XML ? It's great for UI (well, it's used for Android :p).

**Comment by mdsitton** [comment]
I have a huge dislike for XML.

**Comment by Salamandar** [comment]
Hahah, why ? It's powerful yet !

**Comment by mdsitton** [comment]
Its generally annoying to parse, the language also looks very dense if you were to write it by hand. Which makes it difficult to read. The way the language is it will be way larger than an equivelent JSON file just because of the open and closing tags basically being duplicated for everything.

**Comment by Salamandar** [comment]
Okay ^^
I've never seen JSon used to define UI though… But it may exist :p

**Comment by mdsitton** [comment]
I'm going to attempt to do it, if it doesn't work well i can always try something different.

**Comment by Salamandar** [comment]
For YAML there is yaml-cpp. 
It's in the package repositories of lots of Linux distros, so that's pretty cool ^^
For windows, there is the deps/ folder and submodules ;)

**Comment by Salamandar** [comment]
For now I'll just write a YAML file containing everything we might need. Just to have an idea.

**Comment by Salamandar** [comment]
The configuration fileS are parsed (well the code is not complete but we will complete it as we need).
Same for writing the configuration file (the code is "complete" but may be adapted as we need).

`Parameter`s are used to contain the value from command line and config files (we dont want the command line values saved in the config file !), and also the readable name and description (for the config panel). They may change at any moment as they are global values, I may add a member value "needs restart" or smth.

**Comment by mdsitton** [comment]
one goal I have also is to never ever require a full restart.

**Comment by mdsitton** [comment]
imo anything that requires the game to be restarted after changed is just lazy...
