### ISSUE TITLE
Finish the VFS and integrate it with the codebase.

### ISSUE THREAD

**Issue by mdsitton** [OpenRhythm/OpenRhythm#16]
Currently there is a partially complete VFS, however there is still some missing features like merged mounts.

Basically to integrate with the rest of the code all file IO needs to go through the VFS. To make the name VFS make sense we will also want to have it able to perform basic filesystem operations in a cross platform way.

**Comment by Salamandar** [comment]
I don't like the way you set the configuration directories, I'll touch this soon.

**Comment by mdsitton** [comment]
I'm considering just dropping the vfs in favor of something else which I'm calling resource bundles.

**Comment by JamesMoses** [comment]
Sounds good

Sent from Mail for Windows 10

**Comment by mdsitton** [comment]
I'm going to go ahead and close this issue, the VFS code has already been removed from the codebase.
