### ISSUE TITLE
How to save scores

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#18]
Well I want the scores to be saved in a "centralized" user database, and I think we all agreed on this.
That means several things : 
- No more "giving the songs to a friend with my scores" (or giving the whole database ? Meh.)
  - We could implement some sort of "export scores inside the music filetree"
- We have to be able to "detect" when songs are moved, renamed
  - Shasum on the audio file ? Yeah, but that means audio metadata modifications breaks the DB
  - Metadatas inside the ogg file > Hum, as we said, the less we modify the audio files, the better ;)

**Comment by Salamandar** [comment]
EDIT : I'm tired. I meant shasum on the MIDI file. So there are no issues with audio metadatas. And that means we know if the user "cheated" by editing the midi :p

**Comment by mdsitton** [comment]
Yes midi checksum will be the best way to handle this. And the scores should be stored in an SQLite database.

**Comment by mdsitton** [comment]
The only problem with using the full midi checksum is that if additional tracks are added to an old midi but the original one wasn't modified then scores will break. So we could look into doing a checksum at a midi Track Chunk level. and storing a couple midi header values.

**Comment by Salamandar** [comment]
Yeah that's true. But that's also smth pretty rare ^^

**Comment by mdsitton** [comment]
Yeah even so, I'd still like to implement it, because its seriously simple to do lol. It would probably only be ~50 lines of code(other than a dep or class to calculate some sort of checksum)...

**Comment by Salamandar** [comment]
That may be implemented in the music editor then ? Or do you want to store not the file checksum but the track ? 
The problem I see for the track checksum is that you need to parse the file before calculating the checksum. That's a lot of disk access. But calculating the whole file checksum is way lighter.

**Comment by Salamandar** [comment]
It may be nothing, we'll just have to see :)

**Comment by mdsitton** [comment]
Well I can build it into the midi parser as well. And I'm already reading the whole midi file into memory before parsing which makes it way faster lol. So doing another pass over the file won't effect much lol.

**Comment by Salamandar** [comment]
Okay for reading into memory. 
The thing is that I would like to list the whole library at start: that allows searching, mostly. So that means parsing the MIDI for the whole library… Not really efficient. Maybe we can rely first on the file modification date THEN if it differs, on the MIDI by-track checksum ?

**Comment by mdsitton** [comment]
Well I've been working on a faster parseutils toolset. the next thing I want to add support for is memory mapped files. which I think will work very well for partially parsing a midi.

**Comment by mdsitton** [comment]
Before i was using istreams/istringstreams and that wasn't the most efficient thing. So I currently have this FileBuffer struct (I need to turn it into a class here soon and do a bit of refactoring). It  currently reads a full file into a vector internally then when the read_type / peek_type templates are used it takes a pointer to the internal vector storage, and uses offsets based on the position member to read the data. If I implement memory mapped files for win32/linux/osx then I can easily have it use that.

Then we can implement midi parser init options (so stuff like only parse track sequence names use memory mapped files etc.)

**Comment by Salamandar** [comment]
(btw dont wait any answer from me today)

**Comment by mdsitton** [comment]
Alright(probably better to mention that stuff in riot 😛)

**Comment by Salamandar** [comment]
(sure but in Android 7 Riot has a weird bug at launch, a non-cancellable popup, so cant talk on Riot. I'LL remove those comment on github tomorrow)

**Comment by mdsitton** [comment]
Odd I'm on android 7 as well and don't have any issues.

**Comment by mdsitton** [comment]
i'm going to close this as its still way far out.
