### ISSUE TITLE
Change MIDI for another format

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#19]
I don't like MIDI. It's old (thus ***too much*** optimized), a pain to parse, and not so adapted to our needs. I'm sure it's even worse to generate MIDI. And it's not even using seconds for a unit…
If we want to extend to more than guitar, we probably should define a new format (or use an existing format, idk what OSU or RB are using). And if we want to add metadatas like scenes, effects,… too.

**Comment by mdsitton** [comment]
Rock Band uses midi, FoFiX/FoF uses midi, Phase Shift uses midi. There are tons of tools out there already setup to handle midi. People are generally used to working with it at this point. There is a large base of songs out there already.
So nope this is non-negotiable, midi stays.
