### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#20]
Well I've already tried CLdoc and it works pretty good, renders great web pages, with a search engine. The parsing is slow and monothread though.
My core/audio code already implements its (very simple) syntax, and I'll push the cmake changes in the docs branch. Did you have another doc engine in mind ?

**Comment by mdsitton** [comment]
I don't have many thoughts on documentation generation, as i've never actually used it. The only thing i have to say is i refuse to use doxygen, because i always come across those doxygen generated pages and find them basically completely useless.

**Comment by Salamandar** [comment]
Well to be fair I think documentation is important. Event if it's just the public apis.
I agree about doxygen, and that's why I searched alternatives.
CLdoc gives some clean stuff and the parsing is using CLang (yeah, powerful stuff :p ).
There is also Sphinx, already used by some huge projects, but more for python.

**Comment by mdsitton** [comment]
But yeah after reading into CLDoc today it seems pretty awesome. I like how it uses markdown. :+1:

**Comment by Salamandar** [comment]
Yeah, right ? Did you try the docs branch on Windows ? I'd like the CLDoc add to not break CMake on Windows if CLDoc is not installed.

**Comment by mdsitton** [comment]
I haven't tried it yet, I guess I'll try it soon.

**Comment by Salamandar** [comment]
I think we can close that for now ;)
Just a last idea : the Linux Kernel now uses Sphinx so… I think I'll reconsider it ;)
Anyway, doc isn't a big deal for us (it's only "internal" doc, not "public") so if CLDoc works… why change ?

**Comment by mdsitton** [comment]
Well I dislike the RST that sphinx uses by default.. so that is one reason :P
