### ISSUE TITLE
Optional PNG++ ?

### ISSUE THREAD

**Issue by Salamandar** [OpenRhythm/OpenRhythm#26]
I meant to ask you to understand, why Png++ is an optional library ? Why activate/deactivate it and how is it handled in the source code ?

**Comment by Salamandar** [comment]
EDIT : saw how it's handled in the source. But why ? ^^

**Comment by mdsitton** [comment]
It really should just be removed it was implemented before I found stb and I just kept the implementation...

**Comment by Salamandar** [comment]
Ah, okay. So you prefer using the STB ? I mean I have some performance concerns, that's all.

**Comment by mdsitton** [comment]
As long as we have optimization enabled stb_image has similar performance vs libpng and libjpeg based stuff:
https://caedesnotes.wordpress.com/2015/03/23/comparing-performance-stb_image-vs-libjpeg-turbo-libpng-and-lodepng/

**Comment by Salamandar** [comment]
Okay, great then :) By performance I was also thinking about the size footprint of the lib as it's a header only library, but optimization probably removes all that.

**Comment by mdsitton** [comment]
Keep it open or closed? lol

**Comment by Salamandar** [comment]
I wanted to push the changes before :p

**Comment by mdsitton** [comment]
oh ok makes sense.
