### ISSUE TITLE
Possible memory leak in audiotests.cpp

### ISSUE THREAD

**Issue by mdsitton** [OpenRhythm/OpenRhythm#28]
I mentioned this before you merged the branch but you seem to have missed it.

```

    auto *anotherResamplerstream =
        new ORCore::ResamplerStream(anotherOgg, SRC_SINC_MEDIUM_QUALITY);

    auto soundOutput = new ORCore::SoundIoOutput();
```

You call new a couple times but don't delete the allocated memory.

**Comment by mdsitton** [comment]
This is why I would rather you use smart pointers if you can.

**Comment by Salamandar** [comment]
Oh sure. I didnt write really good code for this tests file but yeah I'll fix that.

**Comment by mdsitton** [comment]
Closing this is only related to the old audio code.
